### ISSUE TITLE
軸控系統測試異常

### ISSUE THREAD

**Issue by 3S-En** [NickLee475/3S-FOCI-TMC#11]
線性馬達驅動器X1、X2 Hitachi ADVA-08NL

驅動器控制單獨控制馬達皆正常
1.可正反轉
2.編碼器回授正常

透過PCPG-88軸控卡進行伺服激磁，跳出錯誤 E82.00錯誤代碼

解決方式：需要原廠協助提供Hitachi驅動器使用手冊，以及相關錯誤代碼清單。以便後續處理。

TrayTable入料端，TY軸僅可單方向運轉。CW/CCW
(1) 更改上控輸出脈波電性High/low觸發，依然只能單方向運轉
(2) 交叉比對TX/TY參數，確認設定無誤。
(3) 透過驅動器單獨控制各模組 TX/TY 皆正常可正反轉(驅動器端無誤)
(4) 透過更換TX/TY 控制端皆口(軸卡與驅動器連接控制線材) ，互換後TX僅單方向移動，TY可正常正反轉。

=>研判與控制線材有關係
(5) 重新插拔電腦端控制線以及驅動器端線路 (仍然無法正反轉)
(6) 查詢軸卡配盤線路(TX/TY) 線標與其他軸控相同
(7) 透過更改上控端1P與2P模式驅動測試(仍然無法正反轉)

分析：若因為更改電性可以導致單方向運轉，且改電性可以單方向反轉，合理推估線材接錯!!!
(8) 更換Dir+/Dir-線材進行測試( 正反轉皆失效)
(9) 更換Pulse+/Pulse- 線材進行測試(可正常正反轉)

結論：軸控卡1第二軸，其線材與控制驅動器線路接錯(線標也錯)

**Comment by TMCFrankLee** [comment]
> 線性馬達驅動器X1、X2 Hitachi ADVA-08NL
> 
> 驅動器控制單獨控制馬達皆正常
> 1.可正反轉
> 2.編碼器回授正常
> 
> 透過PCPG-88軸控卡進行伺服激磁，跳出錯誤 E82.00錯誤代碼
> 
> 解決方式：需要原廠協助提供Hitachi驅動器使用手冊，以及相關錯誤代碼清單。以便後續處理。

是否跟附件 P.129 此段說明相關 ?
(5-2) Procedure of Servo ON and the pole position estimation Linear
To start the Offline auto-tuning, click "Servo ON" on the Offline auto-tuning window. If the hole 
sensors are not installed on the motor, the pole position estimation is necessary after the Servo 
ON. Follow the below steps, otherwise the drive trips with Magnetic pole estimation not executed
(E82).

[NB2954X ADVA manual English.pdf](https://github.com/NickLee475/3S-FOCI-TMC/files/10204842/NB2954X.ADVA.manual.English.pdf)

**Comment by TMCFrankLee** [comment]
@3S-En 
看一下這是否可供參考? 對 E82 Error code 有更詳盡的說明，應該是 enable bit7 "Controlword(0x6040)" 進行 Pole position estimation 後即可正常？
![image](https://user-images.githubusercontent.com/117900014/207198421-fcce2b1b-cf72-4096-905d-1ef845dafefe.png)


https://www.scribd.com/document/492556126/ADV-Series-Manual-EN

**Comment by 3S-En** [comment]
E82.00與上電激磁是有關連性的。 由於線性馬達在第一次上電時需要進行尋相位的動作。因此若尋找相位失敗，則會跳此錯誤訊息，無法估測相位。

主要在於上控軸卡發送激磁指令時，驅動器直接回傳錯誤Error. 這邊想確認是否有其他應注意而未注意之處。
若有原廠Hitachi手冊則可以確認如何排除或是可能發生原因。

**Comment by TMCFrankLee** [comment]
@3S-En @GregAcesolution @ChrisChang888 
看來文件應該在這邊? 除了請 AJI 協助外，有其他日本配合廠商可以協助下載相關文件嗎?

https://library.hitachi-ies.co.jp/category/motion_software?doc=6

**Comment by 3S-En** [comment]
透過上控PCPG-88軸卡進行激磁動作，則Hitachi驅動器會跳出錯誤訊息E82.00

因此嘗試以下動作

上控軸卡發送 (1) Alarm clear 以及 (2) 伺服激磁
此種方式可正常尋找相位，並可操作馬達正反轉。

**雖然現況獲得解決。**

Hint：
還是需要協助提供Hitachi 驅動器的使用手冊說明書，這樣才能釐清要如何設定。
是否有相關參數可以調整上電激磁的時間以及循相時間。

**Comment by 3S-En** [comment]
筑波協助提供Hitachi驅動器手冊。

目前重設狀態正常。後續持續追蹤觀察。
